# frozen_string_literal: true

require "json"

namespace :themes do
  ROOT = Pathname(__dir__).join("../..").expand_path
  DATA = ROOT.join("vendor/shadcn/themes.json")

  # Base colours come first in the upstream registry; the rest are accent
  # palettes. Mirrors `apps/v4/registry/base-colors.ts`.
  BASE_COLORS = %w[neutral stone zinc mauve olive mist taupe].freeze

  BANNER = <<~TEXT
    Generated from the shadcn/ui registry (`vendor/shadcn/themes.json`, taken
    from `apps/v4/registry/themes.ts` at the revision in
    `vendor/shadcn/REVISION`) — do not edit by hand, run `rake themes:build`.
  TEXT

  DEFAULT_THEME = "neutral"

  TOKENS_BEGIN = "/* shadcn-tokens:begin"
  TOKENS_END = "/* shadcn-tokens:end */"

  desc "Regenerate the theme stylesheet, the default tokens and the Ruby registry"
  task :build do
    themes = JSON.parse(DATA.read)

    ROOT.join("app/assets/stylesheets/shadcn-themes.css").write(stylesheet(themes))
    ROOT.join("lib/shadcn_view_component/themes.rb").write(registry(themes))
    write_default_tokens(themes)

    puts "Wrote #{themes.size} themes."
  end

  # `:root` and `.dark` in shadcn.css are the default palette, so they are
  # generated from the same JSON as everything else. Hand-maintaining them let
  # them drift: the default look was not actually `theme-neutral`.
  def self.write_default_tokens(themes)
    path = ROOT.join("app/assets/stylesheets/shadcn.css")
    css = path.read
    first = css.index(TOKENS_BEGIN)
    last = css.index(TOKENS_END)

    raise "shadcn.css is missing its shadcn-tokens markers" unless first && last

    path.write(css[0...first] + default_tokens(themes) + css[(last + TOKENS_END.length)..])
  end

  def self.default_tokens(themes)
    theme = themes.find { |candidate| candidate["name"] == DEFAULT_THEME }
    raise "no #{DEFAULT_THEME} theme in #{DATA}" unless theme

    <<~CSS.chomp
      #{TOKENS_BEGIN} — generated by `rake themes:build`, do not edit.
       * The default palette is #{DEFAULT_THEME}; `.theme-*` in shadcn-themes.css
       * overrides these. */

      #{css_block(":root", theme.dig("cssVars", "light"))}

      #{css_block(".dark", theme.dig("cssVars", "dark"))}

      #{TOKENS_END}
    CSS
  end

  def self.stylesheet(themes)
    body = themes.flat_map do |theme|
      name = theme["name"]

      [
        "/* #{theme['title']} */",
        css_block(
          [ ".theme-#{name}", %([data-shadcn-theme="#{name}"]) ],
          theme.dig("cssVars", "light")
        ),
        css_block(
          [ ".dark .theme-#{name}", %(.dark[data-shadcn-theme="#{name}"]) ],
          theme.dig("cssVars", "dark")
        )
      ]
    end

    <<~CSS
      /*
       * shadcn/ui colour themes.
       *
      #{BANNER.strip.gsub(/^/, " * ")}
       *
       * Each theme is a `.theme-<name>` class holding the same token set as
       * `:root`, plus a `.dark .theme-<name>` override — the way shadcn's own
       * site swaps palettes. Put the class on <body>, or on any container to
       * scope a palette to part of the page: custom properties inherit, so
       * everything inside picks them up.
       *
       * The `[data-shadcn-theme]` twin exists so the inline no-flash script can
       * set the palette on <html> before <body> is parsed.
       *
       * Import it after `shadcn.css`. These selectors have the same specificity
       * as `:root`, so source order is what decides.
       */

      #{body.join("\n\n")}
    CSS
  end

  def self.css_block(selectors, vars)
    declarations = vars.map { |name, value| "  --#{name}: #{value};" }
    "#{Array(selectors).join(",\n")} {\n#{declarations.join("\n")}\n}"
  end

  def self.registry(themes)
    entries = themes.map { |theme| registry_entry(theme) }

    <<~RUBY
      # frozen_string_literal: true

      module ShadcnViewComponent
        # The shadcn/ui colour themes.
        #
      #{BANNER.strip.gsub(/^/, "  # ")}
        #
        # Every entry carries the token values for both modes. The matching CSS
        # lives in `app/assets/stylesheets/shadcn-themes.css`; this registry is
        # what `Shadcn::ThemeSelector::Component` reads to build its list.
        module Themes
          ALL = [
      #{entries.join(",\n")}
          ].freeze

          # The neutral greys shadcn offers as a project's base colour.
          BASE_COLORS = ALL.select { |theme| theme[:base_color] }.freeze

          # The accent palettes.
          ACCENTS = ALL.reject { |theme| theme[:base_color] }.freeze

          DEFAULT = "neutral"

          class << self
            def names = ALL.map { |theme| theme[:name] }

            def find(name) = ALL.find { |theme| theme[:name] == name.to_s }

            def exists?(name) = names.include?(name.to_s)
          end
        end
      end
    RUBY
  end

  def self.registry_entry(theme)
    <<~RUBY.chomp.gsub(/^/, "      ")
      {
        name: "#{theme['name']}",
        title: "#{theme['title']}",
        base_color: #{BASE_COLORS.include?(theme['name'])},
        light: {
      #{ruby_hash(theme.dig('cssVars', 'light'))}
        }.freeze,
        dark: {
      #{ruby_hash(theme.dig('cssVars', 'dark'))}
        }.freeze
      }.freeze
    RUBY
  end

  # Four spaces here plus the six `registry_entry` adds lands the pairs one
  # level inside their `light:` / `dark:` key.
  def self.ruby_hash(vars)
    vars.map { |name, value| %(    "#{name}" => "#{value}") }.join(",\n")
  end
end
